{% set name = "pangaea" %}
{% set version = "0.0.3" %}
{% set sha256 = "50dc2c1dd18d20515e238daa7a1435c5fbde36c3be7ea78c4504691631870422" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [win and py3k]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - gazar
    - netcdf4
    - pynio     # [not py3k and not win]
    - wrf-python

test:
  imports:
    - pangaea

about:
  home: https://github.com/snowman2/pangaea
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'An xarray extension for land surface models.'
  description: |
    An xarray extension for land surface models.
  doc_url: http://pangaea.readthedocs.io
  dev_url: https://github.com/snowman2/pangaea

extra:
  recipe-maintainers:
    - snowman2
