travis:
  secure:
    BINSTAR_TOKEN: dAWJlp5GCuWb6toXpqYbqpcQOkPzhC25RhUVncC0LZUdkfpkfqoGwZz/0QlH3O8dowO3x1zPgrEnE30czRCxDKhIdGUi5GsotcoXvpxtAAcLeSTSWXe4buIR+TriM3G7epWPaUpQXvtU6sPTbubLFLWZ42RqJZzq/PchVCHsyQXIpstaFVlXjbDvHh94UDV4r0pXpYC4AzYEXwm6cf62ipYxIU3HmRdvtGWSIo/qijl1HZoVsA0OSNyPqAJ8bCQiDFsNNA51cSWVJGjwRm14X2453pNe7w2mTlT/ReCnVf5wY8RSKhGHb1Rx9K28BLmRL86XDVgikqW0L2zp/AkKpIuGkrOQauHGzqEpMvrzATTPWb4JaW57W1F2mr/3omam93EBushtx2pkSw/wZLd+V7XSEsf5MqEZ6ptVAlOSzsXR4IK6TFxSHgGhcTJplFI9nxeoI+x85nG/neZKpVQdItFYdUCHktrPfAUoL6AOikEWeZddaG0qTC95iE87skW6KS9pOfksxVgyJc8/xcZZDW3AY33tP6HNdb2FLcr3qqkM2kfoCjgPUpoIAN+z+lpnMA9qMIfTslHVaNuXEOi/9XYqRQSRlA5leS27YjOgeX9zIXY0OoBo54VzpU2+UnO3qfewsqPnwX1xwGga7AIFkJo19YQaQyDw5rN4lDwd13M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
